---

- hosts: all
  sudo: yes
  gather_facts: yes


  pre_tasks:

  - name: Update apt cache
    apt: upgrade=yes update_cache=yes

  tasks:

    - include_vars: defaults/main.yml

    - include_vars: test_vars_P5.yml

    - include: tasks/main.yml

    - pip: name=httplib2

    - name: Check to see if Plone 5 is running
      uri:
        url: http://127.0.0.1:5081/Plone
        method: GET
        status_code: 200

    - include_vars: test_vars_P4.yml

    - include: tasks/main.yml

    - name: Check to see if Plone 4.3.x is running
      uri:
        url: http://127.0.0.1:4081/Plone
        method: GET
        status_code: 200
