---

# NOTE: This playbook *adds* rules.
# It does not delete existing rules.

- hosts: all
  sudo: yes
  gather_facts: no

  tasks:

  - name: Include vars from local-configure.yml if found
    include_vars: "{{ item }}"
    with_first_found:
     - local-configure.yml
     - null.yml

  - name: Enable ufw
    ufw: state=enabled policy=allow

  - name: Disable default in
    ufw: direction=incoming policy=deny

  - name: Allow ssh in
    ufw: rule=limit name=OpenSSH

  - name: 80 is open
    ufw: rule=allow port=80 proto=tcp

  - name: 443 is open
    ufw: rule=allow port=443 proto=tcp

  - name: 4949 (munin-node) is open to monitor(s)
    when: install_muninnode|default(True)
    ufw: rule=allow port=4949 proto=tcp from_ip={{ item }}
    with_items: muninnode_query_ips|default([])

