---

- name: varnish package present
  apt: pkg=varnish state=present

- name: Set cache method/size
  replace:
    dest=/etc/default/varnish
    regexp='-s .+"'
    replace='-s {{ proxycache_method }},{{ proxycache_size }}"'
    backup=yes
  notify: restart varnish

- name: Set Varnish front-end port
  replace:
    dest=/etc/default/varnish
    regexp='-a .+ \\'
    replace='-a *:{{ proxycache_port }} \\'
    backup=yes
  notify: restart varnish

- name: Set Varnish admin port to proxycache_port + 1
  replace:
    dest=/etc/default/varnish
    regexp='-T .+ \\'
    replace='-T localhost:{{ proxycache_port + 1}} \\'
    backup=yes
  notify: restart varnish

# We're firewalling off the admin port,
# so we don't need a secret.
- name: Turn off secret
  lineinfile:
    dest=/etc/default/varnish
    regexp="^\s+-S .*$"
    state=absent
    backup=yes
  notify: restart varnish

- name: Set default.vcl from our template
  template:
    src=default.vcl.j2
    dest=/etc/varnish/default.vcl
    backup=yes
  notify: restart varnish
