---

- name: Ensure we have socat if we're load balancing
  when: install_loadbalancer
  apt: pkg=socat state=present

- name: Ensure we have curl
  apt: pkg=curl state=present

- name: Create restart script
  template:
    src=restart_clients.sh.j2
    dest={{ item.plone_target_path|default(plone_target_path) }}/{{ item.plone_instance_name|default(plone_instance_name) }}/scripts/restart_clients.sh
    owner=root
    group=root
    mode=0755
  with_items: playbook_plones
